import {
  Article,
  CVERecord,
  CategoryInfo,
  IncidentMilestone,
  SourceCredibility,
  ThreatLevel,
  ThreatLocation,
  TrendingTopic,
} from '../types';

export const categories: CategoryInfo[] = [
  { id: 'all', label: 'All News', icon: '🌐', color: '#00f0ff' },
  { id: 'malware', label: 'Malware', icon: '🦠', color: '#ff4757' },
  { id: 'data-breach', label: 'Data Breach', icon: '🔓', color: '#ff6b81' },
  { id: 'vulnerability', label: 'Vulnerabilities', icon: '⚠️', color: '#ffa502' },
  { id: 'ransomware', label: 'Ransomware', icon: '💰', color: '#ff4500' },
  { id: 'phishing', label: 'Phishing', icon: '🎣', color: '#eccc68' },
  { id: 'apt', label: 'APT Groups', icon: '🕵️', color: '#a29bfe' },
  { id: 'privacy', label: 'Privacy', icon: '🛡️', color: '#2ed573' },
  { id: 'general', label: 'General', icon: '📰', color: '#00f0ff' },
];

export const currentThreatLevel: ThreatLevel = {
  level: 'high',
  label: 'HIGH',
  color: '#ff4757',
  description: 'Multiple active campaigns targeting critical infrastructure',
};

export const trendingTopics: TrendingTopic[] = [
  { id: '1', name: 'Zero-Day Exploits', count: 284, trend: 'up' },
  { id: '2', name: 'AI-Powered Attacks', count: 196, trend: 'up' },
  { id: '3', name: 'Supply Chain Security', count: 152, trend: 'stable' },
  { id: '4', name: 'Cloud Security', count: 143, trend: 'up' },
  { id: '5', name: 'Quantum Threats', count: 98, trend: 'up' },
  { id: '6', name: 'IoT Vulnerabilities', count: 87, trend: 'down' },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    title: 'Critical Zero-Day Vulnerability Discovered in Major Cloud Platform Affects Millions',
    description: 'Security researchers have uncovered a critical zero-day vulnerability in a leading cloud infrastructure provider that could potentially expose sensitive data of millions of enterprise users worldwide. The flaw, tracked as CVE-2026-1337, allows remote code execution through a crafted API request.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
    source: 'The Hacker News',
    category: 'vulnerability',
    publishedAt: '2026-03-15T02:30:00Z',
    author: 'Security Research Team',
  },
  {
    id: '2',
    title: 'Massive Ransomware Attack Hits Healthcare Systems Across Europe',
    description: 'A sophisticated ransomware campaign has targeted multiple healthcare organizations across Europe, disrupting critical medical services. The LockBit 4.0 variant has encrypted patient records and operational systems in over 30 hospitals.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
    source: 'BleepingComputer',
    category: 'ransomware',
    publishedAt: '2026-03-15T01:15:00Z',
    author: 'Threat Intelligence',
  },
  {
    id: '3',
    title: 'AI-Powered Phishing Campaign Bypasses Advanced Email Security Filters',
    description: 'A new breed of phishing attacks leveraging generative AI has managed to bypass even the most advanced email security solutions. The campaign uses context-aware, perfectly crafted messages that are virtually indistinguishable from legitimate communications.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?w=800&q=80',
    source: 'Krebs on Security',
    category: 'phishing',
    publishedAt: '2026-03-14T22:45:00Z',
    author: 'Brian Krebs',
  },
  {
    id: '4',
    title: 'Nation-State APT Group Lazarus Launches New Supply Chain Attack',
    description: 'The notorious Lazarus Group, linked to North Korea, has been identified as the perpetrator behind a sophisticated supply chain attack targeting popular open-source JavaScript packages. Over 500 npm packages were compromised.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800&q=80',
    source: 'Dark Reading',
    category: 'apt',
    publishedAt: '2026-03-14T20:00:00Z',
    author: 'APT Watch',
  },
  {
    id: '5',
    title: 'Major Data Breach Exposes 50 Million User Records from Financial Platform',
    description: 'A leading fintech platform has confirmed a massive data breach affecting approximately 50 million users. Exposed data includes full names, email addresses, encrypted passwords, transaction histories, and partial payment card information.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1616763355548-1b11cea702ee?w=800&q=80',
    source: 'SecurityWeek',
    category: 'data-breach',
    publishedAt: '2026-03-14T18:30:00Z',
    author: 'Data Breach Team',
  },
  {
    id: '6',
    title: 'New Linux Kernel Malware "ShadowRoot" Evades All Major Detection Tools',
    description: 'Security researchers have discovered a new sophisticated Linux kernel-level malware dubbed "ShadowRoot" that uses novel rootkit techniques to evade detection by all major antivirus and EDR solutions currently available.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80',
    source: 'The Hacker News',
    category: 'malware',
    publishedAt: '2026-03-14T16:00:00Z',
    author: 'Malware Analysis Lab',
  },
  {
    id: '7',
    title: 'EU Passes Landmark Digital Privacy Act with Sweeping New Requirements',
    description: 'The European Union has adopted a comprehensive new digital privacy regulation that imposes strict requirements on data handling, AI transparency, and cross-border data transfers. Companies face fines up to 8% of global revenue.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    source: 'Privacy Affairs',
    category: 'privacy',
    publishedAt: '2026-03-14T14:15:00Z',
    author: 'Compliance Watch',
  },
  {
    id: '8',
    title: 'Critical Vulnerability in Popular VPN Solution Exposes Corporate Networks',
    description: 'A critical authentication bypass vulnerability has been discovered in one of the most widely used enterprise VPN solutions. The vulnerability allows unauthenticated attackers to gain full access to internal corporate networks.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
    source: 'BleepingComputer',
    category: 'vulnerability',
    publishedAt: '2026-03-14T12:00:00Z',
    author: 'Vulnerability Research',
  },
  {
    id: '9',
    title: 'Quantum Computing Breakthrough Raises Immediate Encryption Concerns',
    description: 'A major tech company has announced a quantum computing breakthrough that brings the timeline for breaking current RSA-2048 encryption significantly closer. Cryptography experts are urging immediate adoption of post-quantum algorithms.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
    source: 'Wired Security',
    category: 'general',
    publishedAt: '2026-03-14T10:30:00Z',
    author: 'Crypto Analysis',
  },
  {
    id: '10',
    title: 'Global Botnet Operation Dismantled in Joint Law Enforcement Action',
    description: 'International law enforcement agencies have dismantled one of the largest botnets ever discovered, which had infected over 2 million devices across 120 countries. The infrastructure was used for DDoS attacks and credential theft.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&q=80',
    source: 'Dark Reading',
    category: 'malware',
    publishedAt: '2026-03-14T08:00:00Z',
    author: 'Cybercrime Beat',
  },
  {
    id: '11',
    title: 'State-Sponsored Hackers Target Satellite Communication Systems',
    description: 'A newly identified APT group has been conducting targeted attacks against satellite communication providers serving critical government and military infrastructure. The attacks exploit previously unknown vulnerabilities in ground station software.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80',
    source: 'SecurityWeek',
    category: 'apt',
    publishedAt: '2026-03-14T06:00:00Z',
    author: 'Threat Intel Team',
  },
  {
    id: '12',
    title: 'Major Automotive Manufacturer Hit by Data Breach Leaking Vehicle Telemetry',
    description: 'A leading electric vehicle manufacturer has reported a data breach that exposed detailed telemetry data, location histories, and personal information of over 3 million vehicle owners globally through a misconfigured cloud database.',
    url: '#',
    image: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=800&q=80',
    source: 'Krebs on Security',
    category: 'data-breach',
    publishedAt: '2026-03-13T23:00:00Z',
    author: 'Brian Krebs',
  },
];

export const breakingNews: string[] = [
  '🚨 BREAKING: Critical zero-day in major cloud platform — patch immediately',
  '⚠️ ALERT: Massive ransomware wave targeting European healthcare systems',
  '🔴 UPDATE: 50M user records exposed in fintech platform breach',
  '🔒 ADVISORY: New quantum computing breakthrough threatens current encryption',
  '🕵️ INTEL: Nation-state actors targeting satellite communications infrastructure',
];

export const threatLocations: ThreatLocation[] = [
  { id: 'geo-1', region: 'North America', latitude: 40.7, longitude: -74.0, intensity: 88, incidents: 42, primaryThreat: 'Ransomware' },
  { id: 'geo-2', region: 'Western Europe', latitude: 50.1, longitude: 8.6, intensity: 79, incidents: 35, primaryThreat: 'Data Breach' },
  { id: 'geo-3', region: 'Eastern Europe', latitude: 52.2, longitude: 21.0, intensity: 73, incidents: 29, primaryThreat: 'APT Activity' },
  { id: 'geo-4', region: 'Middle East', latitude: 25.2, longitude: 55.3, intensity: 61, incidents: 21, primaryThreat: 'Phishing' },
  { id: 'geo-5', region: 'South Asia', latitude: 19.1, longitude: 72.8, intensity: 70, incidents: 33, primaryThreat: 'Botnet' },
  { id: 'geo-6', region: 'Southeast Asia', latitude: 1.3, longitude: 103.8, intensity: 55, incidents: 17, primaryThreat: 'Cloud Misconfig' },
  { id: 'geo-7', region: 'Latin America', latitude: -23.5, longitude: -46.6, intensity: 48, incidents: 15, primaryThreat: 'Credential Theft' },
  { id: 'geo-8', region: 'Africa', latitude: -1.2, longitude: 36.8, intensity: 41, incidents: 11, primaryThreat: 'Fraudware' },
];

export const mockCVEs: CVERecord[] = [
  {
    id: 'CVE-2026-1337',
    severity: 'critical',
    score: 9.8,
    vendor: 'CloudSphere',
    product: 'CloudSphere API Gateway',
    publishedAt: '2026-03-15T02:00:00Z',
    summary: 'Improper authentication allows remote code execution via crafted request chains.',
    exploited: true,
  },
  {
    id: 'CVE-2026-1941',
    severity: 'high',
    score: 8.3,
    vendor: 'SecureTunnel',
    product: 'SecureTunnel Enterprise VPN',
    publishedAt: '2026-03-14T10:00:00Z',
    summary: 'Authentication bypass enables unauthorized network access through session replay.',
    exploited: true,
  },
  {
    id: 'CVE-2026-1772',
    severity: 'medium',
    score: 6.7,
    vendor: 'OpenLedger',
    product: 'OpenLedger Sync Service',
    publishedAt: '2026-03-13T09:15:00Z',
    summary: 'Privilege escalation possible in misconfigured multi-tenant deployments.',
    exploited: false,
  },
  {
    id: 'CVE-2026-1209',
    severity: 'low',
    score: 3.9,
    vendor: 'MicroCore',
    product: 'MicroCore Client Agent',
    publishedAt: '2026-03-11T15:20:00Z',
    summary: 'Information disclosure through verbose debug endpoint.',
    exploited: false,
  },
  {
    id: 'CVE-2026-2104',
    severity: 'high',
    score: 8.7,
    vendor: 'NetGrid',
    product: 'NetGrid Edge Controller',
    publishedAt: '2026-03-12T06:40:00Z',
    summary: 'Command injection vulnerability in policy parser reachable pre-authentication.',
    exploited: true,
  },
];

export const sourceCredibility: SourceCredibility[] = [
  {
    source: 'The Hacker News',
    score: 82,
    rationale: 'Fast reporting cadence, strong technical depth, moderate editorial verification cycle.',
    lastAudited: '2026-03-14',
  },
  {
    source: 'Krebs on Security',
    score: 90,
    rationale: 'High investigative quality and reliable sourcing with slower publication throughput.',
    lastAudited: '2026-03-12',
  },
  {
    source: 'BleepingComputer',
    score: 86,
    rationale: 'Consistent incident coverage and strong vendor confirmation signals.',
    lastAudited: '2026-03-13',
  },
  {
    source: 'Dark Reading',
    score: 84,
    rationale: 'Good enterprise context and verified analyst commentary.',
    lastAudited: '2026-03-10',
  },
  {
    source: 'SecurityWeek',
    score: 87,
    rationale: 'Balanced editorial rigor and actionable threat intelligence reporting.',
    lastAudited: '2026-03-11',
  },
];

export const incidentTimeline: IncidentMilestone[] = [
  {
    id: 'tl-1',
    campaign: 'Lazarus Supply Chain 2026',
    date: '2026-02-24',
    stage: 'initial-access',
    detail: 'Compromised maintainer account used to publish tampered package updates.',
  },
  {
    id: 'tl-2',
    campaign: 'Lazarus Supply Chain 2026',
    date: '2026-02-28',
    stage: 'lateral-movement',
    detail: 'Injected credential stealer spread to CI runners across partner ecosystems.',
  },
  {
    id: 'tl-3',
    campaign: 'Lazarus Supply Chain 2026',
    date: '2026-03-03',
    stage: 'exfiltration',
    detail: 'Token bundles exfiltrated to rotating C2 nodes over DNS tunneling.',
  },
  {
    id: 'tl-4',
    campaign: 'Lazarus Supply Chain 2026',
    date: '2026-03-05',
    stage: 'response',
    detail: 'Package revocation and forced key rotation initiated across impacted orgs.',
  },
  {
    id: 'tl-5',
    campaign: 'Lazarus Supply Chain 2026',
    date: '2026-03-09',
    stage: 'recovery',
    detail: 'Baseline rebuild and immutable signing pipeline rolled out.',
  },
];
